### ISSUE TITLE
build failure on Raspberry PI 2 (Raspbian)

### ISSUE THREAD

**Issue by w4mmp** [wd8rde/libExtio_genesis#1]
Hello,
I receive this when attempting to build:
 cd . && /bin/bash ./config.status Makefile depfiles
config.status: creating Makefile
config.status: executing depfiles commands
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"extio_genesis\" -DPACKAGE_TARNAME=\"extio_genesis\" -DPACKAGE_VERSION=\"new\" -DPACKAGE_STRING=\"extio_genesis\ new\" -DPACKAGE_BUGREPORT=\"wd8rde@gmail.com>\" -DPACKAGE_URL=\"\" -DPACKAGE=\"extio_genesis\" -DVERSION=\"new\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBUSB_1_0=1 -DHAVE_LIBPTHREAD=1 -DSTDC_HEADERS=1 -DHAVE_SYS_WAIT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DLSTAT_FOLLOWS_SLASHED_SYMLINK=1 -DHAVE_MEMSET=1 -I.  -I/usr/include/libusb-1.0      -g -O2 -MT libextio_genesis_la-extio.lo -MD -MP -MF .deps/libextio_genesis_la-extio.Tpo -c -o libextio_genesis_la-extio.lo `test -f 'extio.cpp' || echo './'`extio.cpp
libtool: compile:  g++ -DPACKAGE_NAME=\"extio_genesis\" -DPACKAGE_TARNAME=\"extio_genesis\" -DPACKAGE_VERSION=\"new\" "-DPACKAGE_STRING=\"extio_genesis new\"" "-DPACKAGE_BUGREPORT=\"wd8rde@gmail.com>\"" -DPACKAGE_URL=\"\" -DPACKAGE=\"extio_genesis\" -DVERSION=\"new\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBUSB_1_0=1 -DHAVE_LIBPTHREAD=1 -DSTDC_HEADERS=1 -DHAVE_SYS_WAIT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DLSTAT_FOLLOWS_SLASHED_SYMLINK=1 -DHAVE_MEMSET=1 -I. -I/usr/include/libusb-1.0 -g -O2 -MT libextio_genesis_la-extio.lo -MD -MP -MF .deps/libextio_genesis_la-extio.Tpo -c extio.cpp  -fPIC -DPIC -o .libs/libextio_genesis_la-extio.o
In file included from extio.cpp:6:0:
genesis.h:6:40: fatal error: simpleini-master/SimpleIni.h: No such file or directory
compilation terminated.
Makefile:461: recipe for target 'libextio_genesis_la-extio.lo' failed
make: **\* [libextio_genesis_la-extio.lo] Error 1

Thanks,
Ron

**Comment by w4mmp** [comment]
This issue has been resolved.  I found the simple ini source and installed it the required location.

**Comment by wd8rde** [comment]
Sorry, I forgot the simpleini stuff. It is in there now.
