### ISSUE TITLE
The simple ini issue fixed.  Now this error

### ISSUE THREAD

**Issue by w4mmp** [wd8rde/libExtio_genesis#2]
Hello,
I needed to change one of the compiler options:
changed:
libextio_genesis_la_CPPFLAGS = $(USB_CFLAGS) -std=gnu++11
to
libextio_genesis_la_CPPFLAGS = $(USB_CFLAGS) -std=gnu++0x

Nothing would compile without the change.
Now I receive this:

/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"extio_genesis\" -DPACKAGE_TARNAME=\"extio_genesis\" -DPACKAGE_VERSION=\"new\" -DPACKAGE_STRING=\"extio_genesis\ new\" -DPACKAGE_BUGREPORT=\"wd8rde@gmail.com>\" -DPACKAGE_URL=\"\" -DPACKAGE=\"extio_genesis\" -DVERSION=\"new\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBUSB_1_0=1 -DHAVE_LIBPTHREAD=1 -DSTDC_HEADERS=1 -DHAVE_SYS_WAIT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DLSTAT_FOLLOWS_SLASHED_SYMLINK=1 -DHAVE_MEMSET=1 -I.  -I/usr/include/libusb-1.0   -std=gnu++0x   -g -O2 -MT libextio_genesis_la-genesis.lo -MD -MP -MF .deps/libextio_genesis_la-genesis.Tpo -c -o libextio_genesis_la-genesis.lo `test -f 'genesis.cpp' || echo './'`genesis.cpp
libtool: compile:  g++ -DPACKAGE_NAME=\"extio_genesis\" -DPACKAGE_TARNAME=\"extio_genesis\" -DPACKAGE_VERSION=\"new\" "-DPACKAGE_STRING=\"extio_genesis new\"" "-DPACKAGE_BUGREPORT=\"wd8rde@gmail.com>\"" -DPACKAGE_URL=\"\" -DPACKAGE=\"extio_genesis\" -DVERSION=\"new\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBUSB_1_0=1 -DHAVE_LIBPTHREAD=1 -DSTDC_HEADERS=1 -DHAVE_SYS_WAIT_H=1 -DHAVE_FCNTL_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE__BOOL=1 -DHAVE_STDBOOL_H=1 -DLSTAT_FOLLOWS_SLASHED_SYMLINK=1 -DHAVE_MEMSET=1 -I. -I/usr/include/libusb-1.0 -std=gnu++0x -g -O2 -MT libextio_genesis_la-genesis.lo -MD -MP -MF .deps/libextio_genesis_la-genesis.Tpo -c genesis.cpp  -fPIC -DPIC -o .libs/libextio_genesis_la-genesis.o
genesis.cpp:16:9: error: expected primary-expression before '.' token
genesis.cpp:17:9: error: expected primary-expression before '.' token
genesis.cpp:18:9: error: expected primary-expression before '.' token
genesis.cpp:19:9: error: expected primary-expression before '.' token
genesis.cpp:23:9: error: expected primary-expression before '.' token
genesis.cpp:24:9: error: expected primary-expression before '.' token
genesis.cpp:25:9: error: expected primary-expression before '.' token
genesis.cpp:26:9: error: expected primary-expression before '.' token
genesis.cpp:29:9: error: expected primary-expression before '.' token
genesis.cpp:30:9: error: expected primary-expression before '.' token
genesis.cpp:31:9: error: expected primary-expression before '.' token
genesis.cpp:32:9: error: expected primary-expression before '.' token
genesis.cpp:35:9: error: expected primary-expression before '.' token
genesis.cpp:36:9: error: expected primary-expression before '.' token
genesis.cpp:37:9: error: expected primary-expression before '.' token
genesis.cpp:38:9: error: expected primary-expression before '.' token
genesis.cpp:41:9: error: expected primary-expression before '.' token
genesis.cpp:42:9: error: expected primary-expression before '.' token
genesis.cpp:43:9: error: expected primary-expression before '.' token
genesis.cpp:44:9: error: expected primary-expression before '.' token
genesis.cpp:47:9: error: expected primary-expression before '.' token
genesis.cpp:48:9: error: expected primary-expression before '.' token
genesis.cpp:49:9: error: expected primary-expression before '.' token
genesis.cpp:50:9: error: expected primary-expression before '.' token
genesis.cpp:53:9: error: expected primary-expression before '.' token
genesis.cpp:54:9: error: expected primary-expression before '.' token
genesis.cpp:55:9: error: expected primary-expression before '.' token
genesis.cpp:56:9: error: expected primary-expression before '.' token
genesis.cpp:59:9: error: expected primary-expression before '.' token
genesis.cpp:60:9: error: expected primary-expression before '.' token
genesis.cpp:61:9: error: expected primary-expression before '.' token
genesis.cpp:62:9: error: expected primary-expression before '.' token
genesis.cpp:64:2: error: no matching function for call to 'std::vectorGenesis::_BandFilter_t::vector(<brace-enclosed initializer list>)'
genesis.cpp:64:2: note: candidates are:
/usr/include/c++/4.6/bits/stl_vector.h:334:9: note: template<class _InputIterator> std::vector::vector(_InputIterator, _InputIterator, const allocator_type&)
/usr/include/c++/4.6/bits/stl_vector.h:308:7: note: std::vector<_Tp, _Alloc>::vector(std::initializer_list<_Tp>, const allocator_type&) [with _Tp = Genesis::_BandFilter_t, _Alloc = std::allocatorGenesis::_BandFilter_t, std::vector<_Tp, _Alloc>::allocator_type = std::allocatorGenesis::_BandFilter_t]
/usr/include/c++/4.6/bits/stl_vector.h:308:7: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'std::initializer_listGenesis::_BandFilter_t'
/usr/include/c++/4.6/bits/stl_vector.h:294:7: note: std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>&&) [with _Tp = Genesis::_BandFilter_t, _Alloc = std::allocatorGenesis::_BandFilter_t, std::vector<_Tp, _Alloc> = std::vectorGenesis::_BandFilter_t]
/usr/include/c++/4.6/bits/stl_vector.h:294:7: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'std::vectorGenesis::_BandFilter_t&&'
/usr/include/c++/4.6/bits/stl_vector.h:278:7: note: std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = Genesis::_BandFilter_t, _Alloc = std::allocatorGenesis::_BandFilter_t, std::vector<_Tp, _Alloc> = std::vectorGenesis::_BandFilter_t]
/usr/include/c++/4.6/bits/stl_vector.h:278:7: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'const std::vectorGenesis::_BandFilter_t&'
/usr/include/c++/4.6/bits/stl_vector.h:249:7: note: std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type, const value_type&, const allocator_type&) [with _Tp = Genesis::_BandFilter_t, _Alloc = std::allocatorGenesis::_BandFilter_t, std::vector<_Tp, _Alloc>::size_type = unsigned int, std::vector<_Tp, _Alloc>::value_type = Genesis::_BandFilter_t, std::vector<_Tp, _Alloc>::allocator_type = std::allocatorGenesis::_BandFilter_t]
/usr/include/c++/4.6/bits/stl_vector.h:249:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/4.6/bits/stl_vector.h:237:7: note: std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type) [with _Tp = Genesis::_BandFilter_t, _Alloc = std::allocatorGenesis::_BandFilter_t, std::vector<_Tp, _Alloc>::size_type = unsigned int]
/usr/include/c++/4.6/bits/stl_vector.h:237:7: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'unsigned int'
/usr/include/c++/4.6/bits/stl_vector.h:225:7: note: std::vector<_Tp, _Alloc>::vector(const allocator_type&) [with _Tp = Genesis::_BandFilter_t, _Alloc = std::allocatorGenesis::_BandFilter_t, std::vector<_Tp, _Alloc>::allocator_type = std::allocatorGenesis::_BandFilter_t]
/usr/include/c++/4.6/bits/stl_vector.h:225:7: note:   no known conversion for argument 1 from '<brace-enclosed initializer list>' to 'const allocator_type& {aka const std::allocatorGenesis::_BandFilter_t&}'
/usr/include/c++/4.6/bits/stl_vector.h:217:7: note: std::vector<_Tp, _Alloc>::vector() [with _Tp = Genesis::_BandFilter_t, _Alloc = std::allocatorGenesis::_BandFilter_t]
/usr/include/c++/4.6/bits/stl_vector.h:217:7: note:   candidate expects 0 arguments, 1 provided
genesis.cpp: In member function 'bool Genesis::LoadConfigFile()':
genesis.cpp:211:36: error: no matching function for call to 'CSimpleIniTempl<char, SI_GenericNoCase<char>, SI_ConvertA<char> >::LoadData(std::ifstream&)'
genesis.cpp:211:36: note: candidates are:
simpleini-master/SimpleIni.h:602:14: note: SI_Error CSimpleIniTempl<SI_CHAR, SI_STRLESS, SI_CONVERTER>::LoadData(const string&) [with SI_CHAR = char, SI_STRLESS = SI_GenericNoCase<char>, SI_CONVERTER = SI_ConvertA<char>, std::string = std::basic_string<char>]
simpleini-master/SimpleIni.h:602:14: note:   no known conversion for argument 1 from 'std::ifstream {aka std::basic_ifstream<char>}' to 'const string& {aka const std::basic_string<char>&}'
simpleini-master/SimpleIni.h:1412:1: note: SI_Error CSimpleIniTempl<SI_CHAR, SI_STRLESS, SI_CONVERTER>::LoadData(const char_, size_t) [with SI_CHAR = char, SI_STRLESS = SI_GenericNoCase<char>, SI_CONVERTER = SI_ConvertA<char>, size_t = unsigned int]
simpleini-master/SimpleIni.h:1412:1: note:   candidate expects 2 arguments, 1 provided
genesis.cpp: In member function 'bool Genesis::SaveConfigFile()':
genesis.cpp:240:33: error: no matching function for call to 'CSimpleIniTempl<char, SI_GenericNoCase<char>, SI_ConvertA<char> >::Save(std::ofstream&)'
genesis.cpp:240:33: note: candidates are:
simpleini-master/SimpleIni.h:2398:1: note: SI_Error CSimpleIniTempl<SI_CHAR, SI_STRLESS, SI_CONVERTER>::Save(CSimpleIniTempl<SI_CHAR, SI_STRLESS, SI_CONVERTER>::OutputWriter&, bool) const [with SI_CHAR = char, SI_STRLESS = SI_GenericNoCase<char>, SI_CONVERTER = SI_ConvertA<char>]
simpleini-master/SimpleIni.h:2398:1: note:   no known conversion for argument 1 from 'std::ofstream {aka std::basic_ofstream<char>}' to 'CSimpleIniTempl<char, SI_GenericNoCase<char>, SI_ConvertA<char> >::OutputWriter&'
simpleini-master/SimpleIni.h:742:14: note: SI_Error CSimpleIniTempl<SI_CHAR, SI_STRLESS, SI_CONVERTER>::Save(std::string&, bool) const [with SI_CHAR = char, SI_STRLESS = SI_GenericNoCase<char>, SI_CONVERTER = SI_ConvertA<char>, std::string = std::basic_string<char>]
simpleini-master/SimpleIni.h:742:14: note:   no known conversion for argument 1 from 'std::ofstream {aka std::basic_ofstream<char>}' to 'std::string& {aka std::basic_string<char>&}'
Makefile:468: recipe for target 'libextio_genesis_la-genesis.lo' failed
make: *_\* [libextio_genesis_la-genesis.lo] Error 1
ron@squireoaksfarm-radio ~/data/src/libExtio_genesis

**Comment by wd8rde** [comment]
Looks like you have std template problems. The compiler flags are all
figured out by Autoconf configure, so I think there is something wrong with
your build environment.
Maybe send me a complete log of your ./bootstrap, ./configure ./ make
output?

Oh, and I put the SimpleINI stuff in my git. Sorry about that.

**Comment by wd8rde** [comment]
I think this is a C++0x VS c++11 issue, so the problem is your compiler
version. It looks like it doesn't like my use of designated initializers.
You could take them out, just make sure the initializers are in the right
order (I think they already are). I put them in to make things clearer ;P

As far as the other problem, it looks like you didn't have a define in
Simpleini for the SI_SUPPORT_IOSTREAMS. Just update to my latest commit, it
should work now (except for the initializers).

**Comment by wd8rde** [comment]
OK, sorry, I see I did put the -std=gnu++1 in my Makefile.am. Let me play
around with this today, and I will see what I can do.

**Comment by wd8rde** [comment]
OK, I backported my intializers so they work with G++ 4.6.3, looks like you have 4.6.2, so I hope it works.

**Comment by w4mmp** [comment]
Hi,
Thanks!  I will give the new repository a go.   The default release of 
Raspbian is not very up to date.   When I started this project of 
porting OpenExpertSDR to the Raspberry Pi 2, it became a quick decent 
into revision level / dependency hell.

I could do an "out of band" gcc/++ update to 4.7x or 4.8x, but then 
other things break when attempting to compile /build.

73
Ron / W4MMP

**Comment by w4mmp** [comment]
Thanks!  Built perfectly !  Now I can move onto the real purpose of my efforts.   I am attempting to have OpenExpertSDR function with a Peaberry V2 SDR.   This project has a long learning curve for me.  Object oriented programming make my brain hurt.  I am just an old school c programmer.  But learning is always a good thing.
But, thanks again.  
P.S.  It is really nice to work with someone who is responsive and has English as a first language :)
73,
Ron / W4MMP
