### ISSUE TITLE
Modifications for Softrock RXTX and clones

### ISSUE THREAD

**Issue by w4mmp** [wd8rde/libExtio_genesis#3]
Hi Robert,
 Would you let me know what general areas (if you know) that need to be changed to support the Softrock RXTX? Since the Genesis is somewhat similar in that they both use the Si570 my hope is that I can modify your application to be compatible with the Softrock. Actually the rig(s) I have is the Peaberry V2 but its interface API is identical to the Softrock.

73,
 Ron / W4MMP

**Comment by wd8rde** [comment]
Sorry I have been away so long.
I don't really think that modifying my code is the way for you to go. You could take the Extio API layer, the extio.cpp and extio.h files, and go from there. But, the genesis stuff I wrote was all for talking to the Genesis SDR PIC controller, not directly to the DDS. I think I pulled the original source from the Fifi SDR project for the si570.\* files, http://www.ov-lennestadt.de/fifisdr/trac/browser/trunk/Software/LPC/fifisdr/src/i2c/si570.c?rev=175 If any of this code helps, help yourself :)

The extio.\* files are just an interpretation of the API for the Extio DLL as a linux .so file. You can read about that here, http://www.winrad.org/bin/Winrad_Extio.pdf
