### ISSUE TITLE
Change bands for G11

### ISSUE THREAD

**Issue by florintanasa** [wd8rde/libExtio_genesis#4]
Hi,
When change the band for G11 multi-filter  the command send it is B_FILTER and not SET_FILT like G59.

**Comment by wd8rde** [comment]
I think I have a fix for this coded up on the developement branch. I haven't tested it yet though, hopefully I can test it for at least the G59 tonight.
Florin, if you are feeling adventerous, checkout the developement branch and try it out on your G11.

 On linux:
git clone https://github.com/wd8rde/libExtio_genesis.git
cd libExtio_genesis
git checkout developement
./bootstrap
./configure
make
sudo make install
cd {openexpertsdr_dir}/device
ln -s /usr/local/lib/libextio_genesis.so ./

**Comment by wd8rde** [comment]
Florin I had a mistake in the configure.ac that caused ./configure to fail. I just committed the fix.

**Comment by wd8rde** [comment]
Florin, this is working on the G59, please verify the G11 is working now, and I will close this bug.

**Comment by florintanasa** [comment]
It seems to work, in this moment is activity only in 80m.
I try it to compile in windows with some succes but crash when the lib is 
loaded.
I see you move to hidapi lib is a good move in my opinion.

În ziua de marți, 9 februarie 2016, la 14:14:01 EET, WD8RDE a scris:

**Comment by wd8rde** [comment]
I didn't know you were compiling my code in windows :)
So I will make this closed {woo hoo}.
